[package]
name = "faerber"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
"deltae" = "0.3.0"
"image" = "0.24.1"
"lab" = "0.11.0"
"wasm-bindgen" = "0.2.80"

[profile.release]
lto = true
opt-level= 's'
